name:                tuttifrutti
version:             0.1.0.0
synopsis:            Components for KSF Media services
description:         Ready-made components to quickly build KSF Media services
github:              KSF-Media/tuttifrutti
license:             BSD3
license-file:        LICENSE
author:              Fabrizio Ferrai
maintainer:          fabrizio.ferrai@gmail.com
copyright:           2018 KSF Media
category:            Web

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- time
- text
- bytestring
- unliftio
- random
- containers
- rio
- data-has
- these
- these-lens
- semialign
- contravariant
- mtl
- transformers
- errors
- exceptions
- lens
- lens-aeson
- conduit
- conduit-extra
- conduit-combinators # remove once we quit old conduit
- insert-ordered-containers
- unordered-containers
- case-insensitive
- uuid
- psqueues
- retry
- range
- store
- extensible
- constraints
- named >= 0.2
- attoparsec
- directory
- temporary
- regex-pcre
- unjson
- template
# Development
- rapid
# Testing
- hspec
- hspec-expectations
- hspec-expectations-lifted
- tasty
- tasty-golden
- tasty-hspec
- tasty-hunit
- tasty-vcr
- tasty-expected-failure
# Logging
- fast-logger
- template
# Serialization formats
- aeson
- aeson-diff
- aeson-pretty
- yaml
# Servant things
- servant
- servant-server
- servant-client
- servant-swagger
- swagger2
- path-pieces
# Database
- monad-logger
- postgresql-simple
- persistent
- persistent-template
- persistent-postgresql
- resource-pool
# Environment variables
- envy
# Http
- network
- network-uri
- wai
- wai-extra
- wai-cors
- http-api-data
- http-types
- http-client
- http-conduit
- data-vcr
- http-client-vcr
- mime-mail
- smtp-mail

library:
  source-dirs: src
  ghc-options:
  - -Wall

default-extensions:
- AutoDeriveTypeable
- BangPatterns
- BinaryLiterals
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DerivingStrategies
- DoAndIfThenElse
- EmptyDataDecls
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MonadFailDesugaring
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- PartialTypeSignatures
- PatternGuards
- PolyKinds
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators
- TypeSynonymInstances
- ViewPatterns

tests:
  spec:
    main: Main.hs
    source-dirs:
      - test
      - src
    dependencies:
      - tuttifrutti
      - hspec
      - HUnit
      - hspec-expectations-lifted
      - tasty
      - tasty-hunit
      - doctest
