resolver: lts-21.7
packages:
  - .
extra-deps:
  - git: https://github.com/KSF-Media/haskell-template
    commit: 792b8a5e96cd3cb92f15f761f69105b928043d72
  - git: https://github.com/KSF-Media/haskell-vcr
    commit: 827cc172da3910b19676dfb5263a1d43fd38edf4
    subdirs:
      - data-vcr
      - tasty-vcr
      - http-client-vcr
  - git: https://github.com/KSF-Media/rapid
    commit: 5186d5ced42f4bbb4647bf8ef645c8a7d8e4f026
  - git: https://gitlab.com/dpwiz/raven-haskell.git
    commit: 180088b26fb79515627644545955aed5c50d804a
    subdirs:
      - raven-haskell
allow-newer: true
nix:
  enable: false
  packages:
    - postgresql
    - zlib
    - pcre
    - lzma
    - pkg-config
