resolver: lts-21.8
packages:
  - .
extra-deps:
  - git: https://github.com/KSF-Media/haskell-vcr
    commit: 827cc172da3910b19676dfb5263a1d43fd38edf4
    subdirs:
      - data-vcr
      - tasty-vcr
      - http-client-vcr
  - git: https://github.com/KSF-Media/rapid
    commit: 5186d5ced42f4bbb4647bf8ef645c8a7d8e4f026
  - git: https://gitlab.com/dpwiz/raven-haskell.git
    commit: 180088b26fb79515627644545955aed5c50d804a
    subdirs:
      - raven-haskell
  - template-0.2.0.10@sha256:f822de4d34c45bc84b33a61bc112c15fedee6fa6dc414c62b10456395a868f85,987
allow-newer: true
nix:
  enable: false
  packages:
    - postgresql
    - zlib
    - pcre
    - lzma
    - pkg-config
