resolver: lts-13.04
packages:
- .
- location:
    git: https://github.com/KSF-Media/haskell-vcr
    commit: 71a30452e4dd8ef6b9a0d615d2729e4b1ec01b3a
    subdirs:
      - data-vcr
      - tasty-vcr
      - http-client-vcr
  extra-dep: true
allow-newer: true
extra-deps:
- rapid-0.1.4
- template-0.2.0.10
- range-0.2.1.1
- named-0.2.0.0
- extensible-0.5@sha256:8a3ca016244ad8780fc3c1b9d2ff99534718a4e3a40cd69d8145d0fee915ef09
nix:
  enable: false
  packages:
  - postgresql
  - zlib
